project_name: ksapify

builds:
  - binary: ksapify
    id: "ksapify-primary"
    main: ./cli
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X "github.com/bishal7679/ksapify/cli/cmd.BuildDate={{.Env.DATE}}"
      - -s -w -X "github.com/bishal7679/ksapify/cli/cmd.Version={{.Env.VERSION}}"
    env:
      - CGO_ENABLED=0
signs:
  - cmd: cosign
    stdin: '{{ .Env.COSIGN_PWD }}'
    args:
      - "sign-blob"
      - "--key=cosign.key"
      # - '--output-certificate=${certificate}' 
      - "--output-signature=${signature}"
      - "${artifact}"
      - --yes
    artifacts: all
    output: true
